### ISSUE TITLE
specify node environment in package.json

### ISSUE THREAD

**Issue by micnic** [steelbrain/node-fswatcher#3]
Hi @steelbrain, you are using in your module ES6 syntax (classes and promises) which is not available in node.js 0.10 and 0.12, that's why you should specify which node environment may be used with your module like `iojs: 1.0`

**Comment by steelbrain** [comment]
Well, I do have a built folder (which I am planning to remove from repo and keep in npm module)

**Comment by micnic** [comment]
yes, my bad, I was only looking in the root directory of the repository
